### ISSUE TITLE
[bug] Demo broken ? Or whole project ?

### ISSUE THREAD

**Issue by panique** [jpillora/verifyjs#18]
Hey,

currently the basic usage demo on http://verifyjs.com is broken: The demo validates against numbers, and the demo values are "42" and "xx". Remove the values from the form fields and press _submit_ - and it will validate successfully, which it should not :)

I think this gives the project a weird first impression. Can somebody have a look if this is on project side or just a typo etc inside the demo ?

And for sure a big thanks for a very well-looking project!

**Comment by jpillora** [comment]
Incorrect. It should validate successfully. Instead of:

``` html
<input value="xx" data-validate="number">
```

try:

``` html
<input value="xx" data-validate="required,number">
```

this will give you the behaviour that you're looking for.

You are alerted that the project is "In progress" because there are still some bugs surrounding group validations. It should work fine however for single element validations.

**Comment by panique** [comment]
Thanks! I was just irritated.

**Comment by jpillora** [comment]
No worries, I would like to finish this project though I need a reason to
do it at work
